export const PERM = {
  REPORT_VIEW: "REPORT_VIEW",
  EMPLOYEE_VIEW: "EMPLOYEE_VIEW",
  EMPLOYEE_MANAGE: "EMPLOYEE_MANAGE",

  TASK_ASSIGN: "TASK_ASSIGN",

  REQUEST_APPROVE: "REQUEST_APPROVE",
  LEAVE_REQUEST: "LEAVE_REQUEST",

  FINANCE_OVERVIEW: "FINANCE_OVERVIEW",
  ATTENDANCE_SUMMARY: "ATTENDANCE_SUMMARY",
  SALARY_APPROVE: "SALARY_APPROVE",
  TAX_DEDUCTION: "TAX_DEDUCTION",
  SALARY_VIEW: "SALARY_VIEW",

  ACCOUNT_MANAGE: "ACCOUNT_MANAGE",
  INSURANCE_BENEFIT: "INSURANCE_BENEFIT",
  PROFILE_VIEW: "PROFILE_VIEW",
} as const;

export type PermissionCode = (typeof PERM)[keyof typeof PERM];
